version: '3'
services:
  homeassistant:
    restart: unless-stopped
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant_dev
    network_mode: host
    privileged: true
    volumes:
      - ./src/:/config/custom_components/BIR_Waste_Watch
      - ./src/translations:/config/custom_components/BIR_Waste_Watch/translations
      - /etc/homeassistant/config:/config
    environment:
      - TZ=Europe/Oslo