services:
  homeassistant:
    restart: unless-stopped
    image: homeassistant/home-assistant:stable
    container_name: homeassistant_dev
    ports:
      - "8123:8123"
    volumes:
      - ./custom_components/bir:/config/custom_components/bir
      - ha_config:/config
    environment:
      - TZ=Europe/Oslo

volumes:
  ha_config: